### ISSUE TITLE
Issue about Page developer/API/version-8/Configure Authentication.adoc

### ISSUE THREAD

**Issue by stefankugler** [salesagility/SuiteDocs#102]
#### Page with Issue
Typos in PHP-Sourcecode:

**First PHP example code:**
https://raw.githubusercontent.com/salesagility/SuiteDocs/master/content/developer/API/version-8/Configure%20Authentication.adoc
Line 89:
'Accept: application/vnd.api+json',` (there is a ``` at the end of the line).

Line 98:
curl_setopt($ch, CURLOPT_URL, url);
$url instead of url

**Second PHP example code:**
L194 and L205 (same errors).

Maybe add `echo $output;` at the and of the examples.

**Comment by peterson-umoke** [comment]
please @stefankugler , have you been able to successfully login to suitecrm using any of the login methods to get your access token?... if you have, can you guide me through it please.

**Comment by stefankugler** [comment]
Hi,

the example works, but there is a mod_rewrite error in the .htaccess file of suitecrm.
See eg. https://suitecrm.com/suitecrm/forum/installation-upgrade-help/17937-7-10-api-v8-swagger-json-results-in-no-input-file-specified

Here is a quick'n'dirty script for data import from a mysql database using unirest as REST library:
https://gist.github.com/stefankugler/ebc7b9421f7ed93ca3ba874edc4afa29

Maybe move this discussion to the suitecrm forum, if you have further questions.

Best regards,
Stefan

**Comment by pgorod** [comment]
@stefankugler thanks for providing an example, this is always helpful!

But for an import, done in PHP, is there any reason to use the API? Why not use the Beans directly? I would say the API only needs to be used if the job has to be done remotely, or from a different system, but this is not the usual case for imports.

**Comment by pgorod** [comment]
Due to the many changes in the API code and the new documentation for it, I believe this might now be out-dated.

If not, you can open a new issue, but if possible I ask that you please make the suggested edits as a proposed Pull Request, it's easy:

[docs.suitecrm.com/community/contributing-to-docs](https://docs.suitecrm.com/community/contributing-to-docs/)

Thanks!
