### ISSUE TITLE
Issue about Page community/contributing-to-docs/local-setup.adoc

### ISSUE THREAD

**Issue by gymad** [salesagility/SuiteDocs#109]
#### Page with Issue

all page

#### What is wrong, less clear, or missing
I was following the installation guide but after the installation which went correctly and hugo started I've got a white screen
page source is:
```
<pre>
</pre>

```

**Comment by pgorod** [comment]
@gymad I would need to know the error you got when running Hugo to be able to help (and improve the docs).

1. Please try the latest Hugo version

https://github.com/gohugoio/hugo/releases/download/v0.41/hugo_0.41_Linux-64bit.deb

2. If that doesn't solve it, please try compiling with `--enableGitInfo` flag, that might solve it.

According to your feedback I can then improve the page. Thanks.

**Comment by pgorod** [comment]
@gymad any news on this?
