### ISSUE TITLE
Issue about Page developer/Scheduled Tasks.adoc

### ISSUE THREAD

**Issue by frnklnrd** [salesagility/SuiteDocs#118]
#### Page with Issue

https://docs.suitecrm.com/developer/scheduled-tasks/

#### What is wrong, less clear, or missing

In "Example 13.6: Setting the retry count on a scheduled job"

In last line, you wrote:

$scheduledJob->retry = 2;

#### Proposed fixes and/or additions

$scheduledJob->retry_count = 2;

**Comment by pgorod** [comment]
Hi @frnklnrd, thanks for that, you are right!

Do you want to try doing the edit yourself? It's very easy.

https://docs.suitecrm.com/community/contributing-to-docs/simple-edit/

**Comment by pgorod** [comment]
Ok, I made the change myself and I am closing the issue.
