### ISSUE TITLE
Document config_override

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteDocs#138]
Suggestion from @mphilipps [here](https://github.com/salesagility/SuiteCRM/issues/6297#issuecomment-420189466).

We can move what is in this page into the admin guide:

https://docs.suitecrm.com/developer/config/

and then add other options like

`$sugar_config['allow_sendmail_outbound'] = true;`

Note that, to my knowledge, there is no single place out there that lists all available `sugar_config` options :-) but we can build this page incrementally as we come across options and understand how they work.

[This is a good start](https://web.archive.org/web/20160512043806/http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_6.5/Application_Framework/Helper_Classes/Configurator/Core_Settings/), though.

**Comment by likhobory** [comment]
>  there is no single place out there that lists all available sugar_config options 

I suggest to use /admin/Advanced Configuration Options.adoc file, this file already exists in the [Russian documentation](https://docs.suitecrm.com/ru/admin/advanced-configuration-options/).
[This text](http://support.sugarcrm.com/Documentation/Sugar_Versions/7.9/Pro/Administration_Guide/Advanced_Configuration_Options/) was taken from Sugar documentation as a basis.

**Comment by pgorod** [comment]
Thanks. I would also like to translate your very nice Maps page to English, it's pity I don't know any Russian...

**Comment by likhobory** [comment]
I used [Jeff Walter's blog posts](http://www.jjwdesign.com/tag/google-maps/) when translating, maybe it will help you..

**Comment by pgorod** [comment]
Requests for new Documentation will now be tracked in a master list at #444.

Individual requests such as this Issue will be closed, but don't worry, the list will still reference the request - it's just a different way of managing the Issue list.
