### ISSUE TITLE
Issue about Page blog/Customizing-Subthemes.adoc

### ISSUE THREAD

**Issue by phon3** [salesagility/SuiteDocs#158]
#### Page with Issue

https://docs.suitecrm.com/blog/customizing-subthemes/
#### What is wrong, less clear, or missing
The folder layout on my installation is different than what the doc says.
The document directs you to a directory that, in my case, does not exist.
`custom/themes/SuiteP/themedef.php`

My installation looks like this though:
`custom/themes/default/`
and within the default directory is only an 'images' folder.

#### Proposed fixes and/or additions
Display the correct folder structure so anyone else trying to implement a sub-theme will be successful

**Comment by pgorod** [comment]
I sort of assumed people were familiar with the usual way to customize files in SuiteCRM. But you're right, no reason not to make it clearer, right in this text, so people don't have to go searching for answers elsewhere. So I fixed it. Thanks for reporting.

See https://docs.suitecrm.com/blog/customizing-subthemes/
