### ISSUE TITLE
Document Custom Robo Tasks

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteDocs#167]
It'd be nice to have some documentation about Robo and writing custom tasks for it in SuiteCRM.

I got this working already on my own, but not without quite a bit of struggle. It looks like the codebase is built to support custom tasks, but there's no mention of it in the docs or in any issues/commits I can find.

Example custom task (would be located at `custom/lib/Robo/Plugin/Commands/CustomCommands.php`):
```php
<?php
namespace SuiteCRM\Custom\Robo\Plugin\Commands;
use Robo\Task\Base\loadTasks;

class CustomCommands extends \Robo\Tasks
{
    use loadTasks;

    /**
     * This Robo task will deploy a given branch.
     *
     * @param array $opts
     * @option $branch The branch to deploy, e.g. master, development, etc.
     * @usage deploy --branch=master
     */
    public function deploy(array $opts = ['branch' => 'master'])
    {
        $this->say("Hello, world");
        return Robo\Result::success($this, "Deployed successfully.");
    }
}
```

**Comment by pgorod** [comment]
It seems there is already a page for this, although it's very basic:

https://docs.suitecrm.com/developer/automatedtasks/

Do you want to edit it and add your code there?

Maybe also we can add there the list of available tasks:

```
Available commands:
  help               Displays help for a command
  list               Lists commands
 build
  build:suitep       Build SuiteP theme
 code
  code:coverage      Runs code coverage for travis ci
 configure
  configure:tests    Configure environment for testing
 driver
  driver:run-chrome  Download and run the chrome web driver
 fake
  fake:travis        Configures local environment to look like travis
```
