### ISSUE TITLE
Update "how to contribute" to include note on specific hotfix branches

### ISSUE THREAD

**Issue by samus-aran** [salesagility/SuiteDocs#170]
#### Page with Issue

As spoken about in PR https://github.com/salesagility/SuiteDocs/pull/166 that we should inform the community that we prefer separate PRs for the hotfix and hotfix-7.8.x branches if possible due to the difficulties of merging the incompatible of the branches when releasing that causes breaking changes.

#### Proposed fixes and/or additions
E.g of copy.

Note: Due to the differences between the two major branches (master and 7.8.x) the hotfix-7.8.x can not merge into hotfix (hotfix-7.8.x -> hotfix) without breaking changes. Ideally if a fix can be applied to both branches then we request for two separate pull requests.

**Comment by pgorod** [comment]
I made a small update to reflect this.

https://github.com/salesagility/SuiteDocs/commit/e491b0c2c95cdeb697e2c9f0dc64119cffcd86a9#diff-3e936e1a853f5f59f84daffa71e9bde7

https://docs.suitecrm.com/community/contributing-code/bugs/
