### ISSUE TITLE
Field Types description

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteDocs#188]
Quote from PR #187 about  **DynamicDropdown** field:

> Creates a dropdown list from which you can relate a single record from a variety of modules. Only one Flex Relate-type field is allowed per module. Out of the box,  the Flex Relate option is not available for the Accounts, Calls,  Contracts, Meetings, Notes, and Tasks modules.

But this is a description for the [Flex Relate](http://support.sugarcrm.com/Documentation/Sugar_Versions/8.2/Pro/Administration_Guide/Developer_Tools/Studio/#Field_Types)  field and it can create confusion.
I suggest to add separate descriptions for these fields.

**Comment by likhobory** [comment]
@pgorod 
Can you please add some comments about.. ?

**Comment by pgorod** [comment]
Some preliminary work...

My personal notes when studying this:

- the current description is for the Flex Relate field type

- the dropdown field type let's you select a value from the dropdowns defined in Admin / Dropdown editor

- the dynamic dropdown field let's you select a "parent" dropdown, it works like this:

https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/19487-how-to-create-an-associated-dropdown

**Comment by likhobory** [comment]
Exactly what i need, thanks.

**Comment by pgorod** [comment]
I have a list of links to about 50 Forum posts which are like this - extremely useful, and should be made into Documentation pages.

I agree this one would be one of the first to be included.

We should also consider some documentation inside the product. Studio has a nice help column on the right, there's no reason for it not to explain these things.

**Comment by pgorod** [comment]
Yes the list will be public, as an Issue here on Docs site. Coming soon :-)

I am closing this Issue here, I believe it is done.

**Comment by pgorod** [comment]
Sorry, it's not 50 links, it's 71 🤓 

It's here: #206
