### ISSUE TITLE
No info about 7.11.x on Compatibility Matrix

### ISSUE THREAD

**Issue by bdcomp** [salesagility/SuiteDocs#196]
#### Page with Issue
https://docs.suitecrm.com/admin/compatibility-matrix/

#### What is wrong, less clear, or missing
No info about minimum/compatible versions of platforms and packages for the just released SuiteCRM 7.11.x

**Comment by pgorod** [comment]
Thanks for reminding us. I just published the new version's requirements. It's all similar to the previous version, except a minor adjustment to the PHP version.
