### ISSUE TITLE
Issue about Page developer/api/version-8/Requirements.adoc

### ISSUE THREAD

**Issue by helgebe** [salesagility/SuiteDocs#199]
#### Page with Issue
https://docs.suitecrm.com/developer/api/version-8/requirements/
#### What is wrong, less clear, or missing
It does not show the full requirements for calling the api endpoint, which can be confusing

#### Proposed fixes and/or additions
A link to this 
https://docs.suitecrm.com/developer/api/version-8/json-api/#_before_you_start_calling_endpoints
with some text would make it clearer

**Comment by pgorod** [comment]
I am not familiar with the API, and we're short of developer resources to improve documentation now. 

Would you please consider making the edits yourself?

https://docs.suitecrm.com/community/contributing-to-docs/

Thanks!

**Comment by helgebe** [comment]
Pull request added.
