### ISSUE TITLE
Issue about Page developer/api/version-8/JSON-API.adoc

### ISSUE THREAD

**Issue by helgebe** [salesagility/SuiteDocs#200]
#### Page with Issue
https://docs.suitecrm.com/developer/api/version-8/json-api/#_update_encryption_key

#### What is wrong, less clear, or missing
OAuth2’s AuthorizationServer needs to set an encryption key for security reasons. For doing this, please, go to Api/V8/Config/services/middlewares.php and find the row starts with $server→setEncryptionKey('');

#### Proposed fixes and/or additions

should probably be:
OAuth2’s AuthorizationServer needs to set an encryption key for security reasons. For doing this, please, go to Api/Core/Config/ApiConfig.php and find the row "const OAUTH2_ENCRYPTION_KEY".

**Comment by pgorod** [comment]
Fixed in #202

Thanks!
