### ISSUE TITLE
ifdefs in Russian pages

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteDocs#210]
Hi @likhobory!

I'd like to see if we can avoid these constructs in the Russian pages. I work fine on the English version without them, I don't see a reason why we can't get your set-up to work just as well.

```
ifdef::env-github[:imagesdir: ../../../../../master/static/images/ru/user/core-modules/PDFTemplates]

:btn: btn:

ifdef::env-github[:btn:]
```

If you use the absolute links for images, as I wrote in the Guidelines we should start doing from now on, is that enough to solve whatever was bothering you?

**Comment by likhobory** [comment]
Hi Pedro,

I use ifdefs to display images on the github website. So I would like to leave them unchanged. You can safely delete them from their English versions when translating.

**Comment by pgorod** [comment]
I don't understand what do you mean by "the github website"?

Anyway I think if the correct website root is defined, and you use absolute paths, it should work on different places without change...

**Comment by likhobory** [comment]
I use relative links where possible and they are different for GitHub and SuiteDocs sites, for example:
- SuiteDocs
`:imagesdir: ./../../../../images/ru/user/core-modules/PDFTemplates`

- GitHub
`:imagesdir: ./../../../../master/static/images/ru/user/core-modules/PDFTemplates`

**Comment by pgorod** [comment]
Yes, but what is a "Github site", and why do you need it?

Netlify is free, you can open a personal account there if you need one, and it's super-easy to set up. That way you would have the exact same set-up (and it's better, too).

**Comment by likhobory** [comment]
No, I don’t need a personal account, it’s more convenient for me to use the github in the process of translating, and I would like to leave everything as is for Russian files.

**Comment by pgorod** [comment]
Don't worry, I don't want to break your workflow, I am just trying to understand it, and if possible, make it better. But I realize it is probably not possible, that's ok.

So it seems you work by going into a page [like this](https://github.com/salesagility/SuiteDocs/blob/master/content/user/core-modules/Emails.ru.adoc) and hitting "Edit", am I correct? I had no idea you did that.

Didn't you have a good experience with [this local set-up](https://docs.suitecrm.com/community/contributing-to-docs/local-setup/)? I find it very convenient because I can use better tools (find in files, replace in files, etc) and I get to see Asciidoc's full output, just like it will be in the final deployment.

**Comment by likhobory** [comment]
>  I find it very convenient

Agree. Of course, it is very convenient and most of the work I do locally on a separate server, but sometimes I just do not have such an opportunity and I edit some files remotely.
