### ISSUE TITLE
Issue about Search box not working

### ISSUE THREAD

**Issue by quacklin** [salesagility/SuiteDocs#22]
#### Page with Issue

https://suitecrm-docs.netlify.com/user/introduction/getting-started/

#### What is wrong, less clear, or missing

search box on the right does nothing 

#### Proposed fixes and/or additions

tested with chrome browser and firefox browser
proposed solution: enable search on return command or insert a search button

![image](https://user-images.githubusercontent.com/35828263/35425752-d04f771a-025d-11e8-9feb-684a5142a4fb.png)

**Comment by pgorod** [comment]
Hi @quacklin, thanks for being so quick to spot problems and reporting! I'm afraid you were a bit too quick, though :-) 

The site is not even released yet, we're still working on it. The search is working fine in the most recent version, but what you saw was just a preview I had built for a demo a while back. I disabled that domain now.
