### ISSUE TITLE
Issue about Page admin/administration-panel/Google Sync.adoc

### ISSUE THREAD

**Issue by snachodog** [salesagility/SuiteDocs#225]
#### Page with Issue

https://docs.suitecrm.com/admin/administration-panel/google-sync/
#### What is wrong, less clear, or missing
In the section "add credentials to your project" the structure of the URL is unclear. I am uncertain how I am supposed to do this step: "Under ‘Authorized redirect URIs’, you need to fill in the full URI to the ‘saveGoogleApiKey’ Entry Point."

**Comment by pgorod** [comment]
@ApatheticCosmos can you please give me a hand here?

**Comment by ApatheticCosmos** [comment]
@pgorod I'm looking at it now. The example URL is in the picture to the right. I'll see what I can do to explain this part of the procedure more fully.

**Comment by ApatheticCosmos** [comment]
@pgorod @snachodog 
That PR should fix the issue, along with another one.
