### ISSUE TITLE
Issue about Page blog/creating-custom-field-types.adoc

### ISSUE THREAD

**Issue by peterson-umoke** [salesagility/SuiteDocs#233]
#### Page with Issue

https://docs.suitecrm.com/blog/creating-custom-field-types/
#### What is wrong, less clear, or missing
Field Type not successfully been deployed to the database...

**Comment by pgorod** [comment]
If you're having problems with the application, please ask about it in the support forums:

https://suitecrm.com/suitecrm/forum/

These Issues here are simply for changes to the Documentation, not for product support or bug troubleshooting. Thanks.
