### ISSUE TITLE
Most of the API V8 has incorrect path. Missing the /Api/

### ISSUE THREAD

**Issue by patrickstump** [salesagility/SuiteDocs#253]
Most of the documentation under Developer Guid > API Versions > API-Version-8 > JSON API
shows the api path as just /V8/*.
This appears to be incorrect from what I can see in the code.

Looking in the rewrite rules in .htaccess it only show /Api/*

```
--------- DEPRECATED --------
RewriteRule ^api/(.?)$ lib/API/public/index.php/$1 [L]
RewriteRule ^api/(.)$ - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
-----------------------------

RewriteRule ^Api/access_token$ Api/index.php/access_token [L]
RewriteRule ^Api/V8/(.*?)$ Api/index.php/V8/$1 [L]
RewriteRule ^Api/(.*)$ - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

Expected Behavior
Documentation should show "/Api/V8/..."

Actual Behavior
Documentations shows api as /V8/* Missing the /Api/V8

Possible Fix
Update Documentation

Steps to Reproduce
Not Applicable.
Context
This took me a while to figure out what was wrong with my code trying to access the new api.
So time wasted. Once if found the /Api portion, it appears to be working well.

Your Environment
SuiteCRM Version used:7.11.2
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome (latest)
Environment name and version (e.g. MySQL, PHP 7): MariaDB and PHP 72
Operating System and version (e.g Ubuntu 16.04): ubuntu 18.04

**Comment by pgorod** [comment]
I believe this is fixed already. Thanks.
