### ISSUE TITLE
Unable to search on Mobile device

### ISSUE THREAD

**Issue by samus-aran** [salesagility/SuiteDocs#257]
#### Page with Issue

This happens on any page of the website. Click Navigation > enter text into search bar > either hit Enter on your mobile keypad or Click the search icon... Nothing happens.

#### Proposed fixes and/or additions
Review the styling incase the search icon is blocked by an overlay.

Phone: Google Pixel 2, Chrome

*I'll add a image when I'm on desktop*
![Screenshot_20190404-075715](https://user-images.githubusercontent.com/4041275/55535774-01721f80-56b0-11e9-99c3-c9a059a16fe3.png)

**Comment by pgorod** [comment]
Yes, I can see it happening, it seems to be a CSS problem, the Dropdown with the search results (find-as-you-type) isn't visible on small screen sizes, although it's still there in the HTML... strange...

**Comment by pgorod** [comment]
The Github for our Theme is this:
https://github.com/matcornic/hugo-theme-learn

... in case we need to ask about this issue there, or if we come up with a fix and want to contribute.
