### ISSUE TITLE
Add documentation for ACLs

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteDocs#260]
#### What is wrong, less clear, or missing
ACLs (Access Control Lists) aren't documented despite there being a decent bit of code in SuiteCRM to facilitate their usage. e.g. `ACLRole->getUserRoleNames()`, `$this->bean->ACLAccess('edit')`, `ACLController::checkAccess()`, `ACLController::displayNoAccess()`, etc. It'd be nice to have some documentation on how they can be used to restrict access to certain views depending on a user's roles, ownership, etc.

#### Proposed fixes and/or additions
Add a page on ACLs and how to use them, with examples.

**Comment by pgorod** [comment]
Requests for new Documentation will now be tracked in a master list at #444.

Individual requests such as this Issue will be closed, but don't worry, the list will still reference the request - it's just a different way of managing the Issue list.
