### ISSUE TITLE
Document how to use popups

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteDocs#262]
#### Page with Issue
There's an example of a popupdefs file here, but it doesn't really explain how to make a new view with the Popup feature: https://docs.suitecrm.com/developer/metadata/

#### What is wrong, less clear, or missing

There's not documentation on how to create a new custom PopupView in SuiteCRM.

#### Proposed fixes and/or additions

There should be a page explaining:

- How to use popupdefs
- How to create a view that extends PopupView
- How to add a link (via an `onclick` HTML attribute is how the Changelog popup works, for example) to open the Popup, and what the parameters of the popup JS function are.

**Comment by pgorod** [comment]
Requests for new Documentation will now be tracked in a master list at #444.

Individual requests such as this Issue will be closed, but don't worry, the list will still reference the request - it's just a different way of managing the Issue list.
