### ISSUE TITLE
Add documentation for making custom Smarty template files

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteDocs#264]
#### Page with Issue
https://docs.suitecrm.com/developer/views/

#### What is wrong, less clear, or missing

The page doesn't have anything mentioning the ability to create custom HTML pages using Smarty `.tpl` files. I've actually been just using PHP heredocs and putting the HTML inside my controllers thus far, and assumed it wasn't possible to separate the two. ([see this StackOverflow answer for an example of how to use the Smarty templates in a custom view](https://stackoverflow.com/a/38918990))

#### Proposed fixes and/or additions

Add a section to the Views documentation (or a whole new page) about creating custom `tpl` files, using them in view PHP files, where they should go in the `custom/` directory, etc. Separation of concerns is nice, so I think documenting this would make people's custom modules much better :)

**Comment by connorshea** [comment]
It looks like this commit is a pretty good example of how to convert HTML embedded in PHP to a Smarty template: https://github.com/salesagility/SuiteCRM/commit/ce06cf4ce00289b3f81dfbc72a82630aa6cca130

**Comment by pgorod** [comment]
Creepy coincidence, I also recommended one of Dillon's commits as a Smarty lesson [earlier today](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/26951-email-tamplate-question#87762)

😄
