### ISSUE TITLE
Sidebar not scrolling

### ISSUE THREAD

**Issue by digitalmcgrath** [salesagility/SuiteDocs#28]
#### Page with Issue
[http://docs.suitecrm.com/developer/]([http://docs.suitecrm.com/developer/])

#### What is wrong, less clear, or missing
With a resolution of 1366x768 the sidebar is not scrolling to show all of the developer guide.

**Comment by pgorod** [comment]
There used to be a scroll-bar in the sidebar, now it's gone for some reason, I'll look into it, thanks for reporting.

**Comment by pgorod** [comment]
This is proving tricky to solve (I didn't touch the scroll-bar, this is just a weird side effect from some other changes I made. 

So I decided to simply revert back to the last good version (it was ok yesterday, so not much is lost). So now the site works and I can look for the problem more calmly.

(notifying @lennyhorstink of this development)

**Comment by pgorod** [comment]
Ok, this is fixed now. I committed one of the deadly sins of web content authoring, a missing closing `div` tag.

Oh, the irony of making a commit message called `final fixes` and breaking the site... lesson learned.

Thanks @digitalmcgrath for reporting this immediately, it was very helpful.
