### ISSUE TITLE
Add documentation for SuiteP theme basics/fundamentals

### ISSUE THREAD

**Issue by samus-aran** [salesagility/SuiteDocs#291]
#### Page with Issue

NEW PAGE/STRUCTURE

Sprint 12 - Task to document as much as possible about customising the current SuiteP theme.
Topics include:

- Creating Fonts from Icons
- File Paths to Icons
- List of Fonts & Colours Used
- Sass Compiler
- Adding new Sass File

**Comment by pgorod** [comment]
There is some (not much) material here:

https://docs.suitecrm.com/blog/customizing-subthemes/

A simple docs page that would definitily help is a tutorial teaching how to fix a CSS style, for beginners: finding out which one from the Browser's developer console, adding the new style in custom dir.
