### ISSUE TITLE
Write new Email Module documentation

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteDocs#3]
This requires a lot of study and experimentation before starting to write... 

- different types of Email accounts
- where to go to set them up
- how to test them
- different Email option that can be set
- how to use in-built Email client
- etc

Let's start with something short and simple, and build from there...

**Comment by CBeechey** [comment]
Good progress made on study of Emails module and mail settings, have notes to work from for documentation write up and have started on screenshots.

**Comment by pgorod** [comment]
Congratulations on this Documentation, it's looking really nice!

**Comment by pgorod** [comment]
Hey Claire, what about mentions, do you get the notifications? @CBeechey
