### ISSUE TITLE
Foreign keys in vardefs

### ISSUE THREAD

**Issue by Abuelodelanada** [salesagility/SuiteDocs#309]
#### Page with Issue

If this PR is merged: https://github.com/salesagility/SuiteCRM/pull/7617
We should add a section in [vardefs](https://docs.suitecrm.com/developer/vardefs/)

explaining this new `reference_options`:

```php
            'foreignTable' => 'campaigns',
            'foreignField' => 'id',
            'reference_option' => array(
                'on' => 'DELETE',
                'option' => 'CASCADE',
            ),
```

Also we should document the options `foreignTable` and `foreignField` that are not in the docs

**Comment by jack7anderson7** [comment]
Hi @Abuelodelanada,

I am closing this as you have closed your PR in association with this docs change.

Thanks,
Jack
