### ISSUE TITLE
Issue about Page developer/api/version-8/JSON-API.adoc

### ISSUE THREAD

**Issue by h8hjoshi** [salesagility/SuiteDocs#314]
#### Page with Issue
https://docs.suitecrm.com/developer/api/version-8/json-api/#_get_relationship

#### What is wrong, less clear, or missing
The documentation for the Get relationship API seems incorrect:
- There is no id in the URL
- The available parameters: fields, page, sort, filter are not supported
- The example below is incorrect: V8/module/Accounts?fields[Accounts]=name,account_type&page[size]=4&page[number]=4

#### Proposed fixes and/or additions
- The URL should be changed to : 
GET {{your-SuiteCRM-url}}/V8/module/{moduleName}/{id}/relationships/{relation}
- More clarity regarding the supported parameters
- Example:
GET 
V8/module/Accounts/2f6593b6-001a-c11a-98cb-5d3c60b3699c/relationships/account_notes

**Comment by pgorod** [comment]
@jhrishi23 thanks for raising this issue. Could you please make the edits yourself? I am not familiar with the API, I never used it, and I am afraid I could make some mistake editing the Documentation.

It's easy: https://docs.suitecrm.com/community/contributing-to-docs/simple-edit/

**Comment by pgorod** [comment]
@Dillon-Brown could you please have a look at this and either

* make these edits if you feel they're really quick
* instruct me to close this if it's not really important, or if it's outdated
* give me some idea about how to progress this, or who else to ask for help

Thanks!

**Comment by pgorod** [comment]
Fixed in #452

Thanks!
