### ISSUE TITLE
Missing "generate_select" => true, in code example

### ISSUE THREAD

**Issue by ildarius** [salesagility/SuiteDocs#323]
#### Page with Issue
https://docs.suitecrm.com/developer/appendix-a-code-examples/

#### What is wrong, less clear, or missing
Missing "generate_select" => true after the 

           array('import_function_file' => 'custom/modules/Cases/IncidentUtils.php',),

#### Proposed fixes and/or additions
It should be:

           array('import_function_file' => 'custom/modules/Cases/IncidentUtils.php',),
           "generate_select" => true,

Otherwise the code example get_cases_by_incident() will generate an error because SugarBean class will be expecting a string instead of an array

**Comment by samus-aran** [comment]
Hey @ildarius 
You can edit this page yourself as a contribution :smile:
For simple one line fixes you can go to the problem page and click on the "Edit this page" on the top right of the main form.

![Screenshot_2019-08-09 Appendix A - Code Examples Docs](https://user-images.githubusercontent.com/4041275/62764207-3be83080-ba85-11e9-9885-60d7d15097f3.png)
 
That should take you to the GitHub web editor where you can make a commit and push up to a forked repo (all taken care of via the web interface).

**Comment by ildarius** [comment]
Hi Ashley

Confirmed, thank you I just updated it.

Have a good day

**Comment by pgorod** [comment]
@ildarius maybe something went wrong when you were saving it, I don't see your update.

Make sure you go through all these steps here
https://docs.suitecrm.com/community/contributing-to-docs/simple-edit/

Thanks once again.

**Comment by Dillon-Brown** [comment]
Hi @ildarius, I think I see the changes you made on your fork of SuiteDocs. All you would need to do now is click on "Create pull request" here: https://github.com/salesagility/SuiteDocs/compare/master...ildarius:patch-2

**Comment by ildarius** [comment]
Hi everyone

Confirmed thank you! Still getting the hang of it :)

**Comment by ildarius** [comment]
Just clicked "Create pull request", if it's not working I'll go through
Pedro's documentation again

**Comment by Dillon-Brown** [comment]
@ildarius Looks good to me. Thanks!
