### ISSUE TITLE
Update Releases Bar Chart to Gantt Style.

### ISSUE THREAD

**Issue by mcarpenterjr** [salesagility/SuiteDocs#327]
This page -> https://docs.suitecrm.com/admin/Roadmap/

The roadmap page in the admin section has/had an incomplete Gantt chart, it should be finished and styled to match the SuiteDocs theme.

I will submit a WIP:PR  shortly. I've completed most of the work on cloning the current release chart.

**Comment by pgorod** [comment]
@mcarpenterjr Hey, how are you? Did you get anywhere with this before being swept off in some other direction? Do you care to share your work in a Draft PR, even it's still incomplete? Thanks

**Comment by pgorod** [comment]
BTW, we updated our Theme and I believe that brings in a new version of Mermaid, I am not sure if that will be helpful or detrimental :-)

**Comment by jack7anderson7** [comment]
Hi @mcarpenterjr, 

I'm closing this issue as it is no longer valid.

Thanks,
Jack
