### ISSUE TITLE
Extra ` in API docs

### ISSUE THREAD

**Issue by Dillon-Brown** [salesagility/SuiteDocs#328]
#### Page with Issue

https://docs.suitecrm.com/developer/api/version-8/configure-authentication/

#### What is wrong, less clear, or missing
Just to note, the v8-API docs have an extra ` in the ```Example Request (PHP):```.

#### Proposed fixes and/or additions
I can make a PR for this if nobody else gets around to it :).

**Comment by pgorod** [comment]
Fixed in https://github.com/salesagility/SuiteDocs/commit/bf937fa3cadd5a0028a960a88a228b479b6f8e49
