### ISSUE TITLE
Mention how to enable stack traces in Logging docs.

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteDocs#341]
#### Page with Issue
https://docs.suitecrm.com/developer/logging/

#### What is wrong, less clear, or missing

There's no mention of how to enable stack traces in suitecrm.log.

#### Proposed fixes and/or additions
Mention the `show_log_trace` config option in the logging docs.

See also [this line](https://github.com/salesagility/SuiteCRM/blob/ef1b41965c056937894dd3018d3b149c9c25a9a9/include/SugarLogger/SugarLogger.php#L225) and [this line](https://github.com/salesagility/SuiteCRM/blob/ef1b41965c056937894dd3018d3b149c9c25a9a9/include/SugarLogger/SugarLogger.php#L172).

**Comment by pgorod** [comment]
Are you aware that this is also an option on the UI?

Admin / System settings / Display stack trace of errors

**Comment by connorshea** [comment]
@pgorod that displays it in the interface, I only want it in the `suitecrm.log`

**Comment by pgorod** [comment]
Hhm I didn't know that. Even with `display_errors=Off` in `php.ini`?

**Comment by pgorod** [comment]
❔

**Comment by pgorod** [comment]
Requests for new Documentation will now be tracked in a master list at #444.

Individual requests such as this Issue will be closed, but don't worry, the list will still reference the request - it's just a different way of managing the Issue list.
