### ISSUE TITLE
SuiteCRM-Web-Analytics Error while installing

### ISSUE THREAD

**Issue by opensourcecrm** [salesagility/SuiteDocs#348]
#### Page with Issue

HTTP Status 404 Error:

Everything got installed properly even tomcat is running but when we try with this command :
" tail -f tomcat/logs/catalina.out "we are facing errors and the server is stopping 

![image](https://user-images.githubusercontent.com/17160050/65833289-50f67880-e2ec-11e9-9af7-a68f501eb244.png)

**Comment by pgorod** [comment]
@harrisward can you please have a look at this? Thanks

**Comment by harrisward** [comment]
Can you attach the catalina.out log for me to look at please?

**Comment by opensourcecrm** [comment]
@harrisward We solved it and the system is working now on the port. Actually it is an issue with JDK11

**Comment by harrisward** [comment]
@opensourcecrm Thats correct. You need to use OpenJDK8 for SuiteCRM Analytics. Support for JDK 11 will be coming soon. Glad you got it sorted!

**Comment by opensourcecrm** [comment]
Can we get in touch with you directly to get some information on how to change the login details how to switch SuiteCRM DB and few more inputs to customize the SuiteCRMAnalytics.

**Comment by harrisward** [comment]
Im more than happy to help on the forums! 

https://suitecrm.com/suitecrm/forum/suitecrm-analytics
