### ISSUE TITLE
Broken link in API docs - Issue about Page developer/api/API-4_1.adoc

### ISSUE THREAD

**Issue by coccoinomane** [salesagility/SuiteDocs#355]
#### Page with Issue
https://docs.suitecrm.com/developer/api/api-4_1/

#### What is wrong, less clear, or missing
The link to the "brand new v8 REST API" is broken.
This might mislead users because the page is prominent in Google Search results.

#### Proposed fixes and/or additions
I guess the link should point to one of these two URLS, but I am not sure what the difference is:

* https://docs.suitecrm.com/developer/api/developer-setup-guide/
* https://docs.suitecrm.com/developer/api/postman-setup-guide/

Both URLs are accessible from the parent API Docs page: https://docs.suitecrm.com/developer/api/.

**Comment by wenzdey** [comment]
I went back to the check the old version-8 page and saw it's a combination of both developer-setup-guide and postman-setup-guide new pages. PR has been opened to link to main API page.

**Comment by pgorod** [comment]
Fixed in #358 

Thanks!
