### ISSUE TITLE
Copying to clipboard takes the line numbers with it

### ISSUE THREAD

**Issue by gitbnw** [salesagility/SuiteDocs#36]
#### Page with Issue

https://docs.suitecrm.com/developer/api/1.-api-4_1/

#### Proposed fixes and/or additions
It would be nice to easily copy from the examples without having to delete the line numbers :smiley:

**Comment by pgorod** [comment]
Thanks @gitbnw I hadn't noticed the stuff we imported from Jim Mackin's book had hard-coded line-numbers in there.

@FinnT97 maybe next week you could take a look at this and remove line-numbers from all the stuff in the Developer Guide. This is assuming Asciidoc has a way to auto-add line numbers... let me see, [here it is](http://mrhaki.blogspot.pt/2014/08/awesome-asciidoc-adding-line-numbers-to.html) :-)

**Comment by FinnT97** [comment]
Thanks for raising this issue,

I've removed the line numbers from all of the code examples

We're still looking at ways we can add line numbers automatically without them being selectable, but this is a short-term solution :smile:
