### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by daniloff200** [salesagility/SuiteDocs#363]
As a native Ukrainian speaker, I can help with translation. Does it make sense? 
If so, please, assign this issue to me

**Comment by pgorod** [comment]
Hello daniloff200. Yes of course collaboration from all languages is very interesting to have. Thanks for offering to help!

But regarding the Documentation site, we do need to keep it relatively small and tidy, for maintenance and performance reasons. So we will only include an additional language when it is sufficiently complete. How much effort do you think you can spend on this? Do you think others will also help you out?

If you want, I can create a new `Ukranian` branch for you. You can work there while you learn, and while you develop the translation. But the final decision to integrate onto the main site will have to be dependent on how complete and active it actually becomes.

**Comment by daniloff200** [comment]
Hey @pgorod!

I see, that currently there's a Russian localisation. Is it 100% complete? I know Russian, and Ukrainian is 30-40% same, as Russian, so, it will be easy for me.
I can translate all the files, as in Russian transltation

**Comment by pgorod** [comment]
What do you think, @likhobory, is the Russian translation 100% complete? Maybe it's 110% complete because there are parts that the English version still doesn't have ;-)

Ok @daniloff200 I will create a `Ukrainian` branch for you, please put your work there and we can merge bit by bit as you work, and browse the site with the Netlify previews.

**Comment by pgorod** [comment]
Branch is created. Have a look at this Issue (and associated PR) for an idea on how to start:

#352

And of course make sure you get this working for you:
https://docs.suitecrm.com/community/contributing-to-docs/local-setup/

**Comment by likhobory** [comment]
> is the Russian translation 100% complete? Maybe it's 110% complete because there are parts that the English version still doesn't have ;-)

 No, It's 100% complete for `admin` and `user` sections. 
* The contents of the `Advanced Configuration Options` file in the Russian version is more detail. For all other unique Russian files full English-language analogues were created.
* I did not translate the contents of the `Developer's Guide` section.
* It's 100% complete for `Contributing to the Documentation` section in the `Community Guide`.
* The blog posts have been copied 'as is', but I'm translating your last blog.

@daniloff200 Будут вопросы - обращайтесь, сюда или на мыло, поможем чем сможем :)

**Comment by pgorod** [comment]
I'm going to close this issue since it's not necessary for the progress of the work. Whenever some translations are ready you can create a PR and we can discuss things there. Tell me if you need further help. Thanks.
