### ISSUE TITLE
Wrong information (Upgrading SuiteCRM) 

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteDocs#37]
https://docs.suitecrm.com/admin/installation-guide/3.upgrading/

Quote1 from the first paragraph:
> There is currently no silent upgrade path available for SuiteCRM.

Quote2 from the upgrade considerations:
> Use the Silent Upgrade method through the command line interface...

**Comment by pgorod** [comment]
We do have a method, it's legacy from Sugar...
I wonder if this works

http://support.sugarcrm.com/Documentation/Sugar_Versions/6.5/Pro/Installation_and_Upgrade_Guide/#Upgrading_Via_Silent_Upgrader

Anyway I'll fix the documentation here. Thanks.
