### ISSUE TITLE
Types of Issue Labels should be included in SuiteDocs

### ISSUE THREAD

**Issue by cameronblaikie** [salesagility/SuiteDocs#384]
#### Proposed fixes and/or additions
Types of Issue Labels should be included in the Contributing code page.

**Comment by Dillon-Brown** [comment]
To note, we have a small section on this already here: https://docs.suitecrm.com/community/raising-issues/

It would just need updated with what's in the ```SuiteCRM/.github``` or potentially also into a more appropriate place / it's own page.

**Comment by pgorod** [comment]
Maybe Issue labels can go here
https://docs.suitecrm.com/community/raising-issues/

**Comment by pgorod** [comment]
But the PR labels would go somewhere else... but since some of them are common, maybe a separate `Labels` page is the way to go...

**Comment by pgorod** [comment]
Completed in 1655a14fa6b30dec957f5528edceabbc18eb986e
