### ISSUE TITLE
Issue about Page developer/automatedtasks/Sass.adoc

### ISSUE THREAD

**Issue by mreschke** [salesagility/SuiteDocs#395]
#### Page with Issue
https://docs.suitecrm.com/developer/automatedtasks/sass/

It says command is build:suitep, its actually build:suite-p (with a dash)

**Comment by pgorod** [comment]
Thanks. Do you want to edit the site yourself? It's wiki-style, everybody can edit.

https://docs.suitecrm.com/community/contributing-to-docs/simple-edit/
