### ISSUE TITLE
Hindi translation of Docs

### ISSUE THREAD

**Issue by anchal7299** [salesagility/SuiteDocs#397]
I want to help in making the docs available in hindi as well.

**Comment by pgorod** [comment]
Hello anchal7299. Yes of course collaboration from all languages is very interesting to have. Thanks for offering to help!

But regarding the Documentation site, we do need to keep it relatively small and tidy, for maintenance and performance reasons. So we will only include an additional language when it is sufficiently complete. How much effort do you think you can spend on this? Do you think others will also help you out?

Once you have some work done, if you want, I can create a new `Hindi` branch for you. You can work there while you learn, and while you develop the translation. But the final decision to integrate onto the main site will have to be dependent on how complete and active it actually becomes.

**Comment by pgorod** [comment]
I'm going to close this issue since it's not necessary for the progress of the work. Whenever some translations are ready you can create a PR and we can discuss things there. Tell me if you need further help. Thanks.
