### ISSUE TITLE
Remove Click-To-Call description (English part)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteDocs#414]
See https://github.com/salesagility/SuiteCRM/pull/7879

I suggest to remove this string from the [System.adoc](https://github.com/salesagility/SuiteDocs/blob/master/content/admin/administration-panel/System.adoc#proxy-settings) file and add the correct description to the 'Proxy Settings' section.

**Comment by pgorod** [comment]
Thanks Greg

fixed in https://github.com/salesagility/SuiteDocs/commit/8805b0a33fda1e2a69487cc0b766c31a98be6004
