### ISSUE TITLE
Issue about Page community/Raising Issues.adoc

### ISSUE THREAD

**Issue by Dillon-Brown** [salesagility/SuiteDocs#416]
#### Page with Issue

Not sure if I'll have time to take a look at this so thought I'd just raise it here in case someone has some spare time:

https://docs.suitecrm.com/community/raising-issues/

#### What is wrong, less clear, or missing
Noticed the label section is a bit out of date with what we are currently using the in the main SuiteCRM repo.

#### Proposed fixes and/or additions
There should be an up to date list of the current labels here that could be moved across (Perhaps not all of it though): https://github.com/salesagility/SuiteCRM/blob/master/.github/CONTRIBUTING.md

**Comment by pgorod** [comment]
Isn't this the same as 
#384
#385
?

**Comment by Dillon-Brown** [comment]
> Isn't this the same as
> #384
> #385
> ?

Yes lol. Thanks :P

**Comment by pgorod** [comment]
You can nudge Camy to finish that work ;-)
