### ISSUE TITLE
List of requests for documentation write-ups

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteDocs#444]
## What this Issue is for

Every now and then someone asks for Documentation on some part of SuiteCRM that is not yet documented. These Issues sometimes are dealt with soon, but often they are just left abandoned.

From now on we'll just close those issues and insert a new entry here. This way we can track all Issues together and have a central point to manage the work of the Community Documentation Team as it goes through these requests.

#### Comments on requests

If you have a comment to make about a specific Request for Documentation, go into the specific Issue and comment there. This applies even if the Issue is closed (which normally it will be!). It is still referenced from here.

#### New requests

If you need something to be documented, but are not ready to do it yourself (by submitting a PR), then open a new Issue with your request. This issue can be discussed, and will be closed and a reference will be created here in the master list.

#### Taking up an issue to work on it

Are you ready for some writing? Then leave a comment on the specific issue and we'll assign it to you.

**Comment by pgorod** [comment]
## List of Requests for writing Documentation

* Add documentation on using composer-merge with SuiteCRM #273
* Add documentation for ACLs #260

**Comment by samus-aran** [comment]
Appears all the request have been completed on this list.

**Comment by pgorod** [comment]
Hey Ashley, how are you? 👋 

"Appears", yes, but not really 😅 

The point of this issue here is to be an ongoing list. So I closed all the other Documentation-request issues, leaving a reference here. These requests are easy to make, so people make them a lot, but they tend to get zero attention because actually writing docs is tiresome.

This way the main list would be uncluttered with things that tend to stay there forever, but there would still be a place to keep user's requests and for anyone willing to work on Documentation to come and look for requests.
