### ISSUE TITLE
htmltest and uppercase hashes in Russian files

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteDocs#446]
The comments in this past issue pretty much explain our problem: #236

Some Russian files have links which use uppercase letters in the hashes, for example, 

`ru/admin/administration-panel/studio/index.html --> ../developer-tools/#_Студия`

Then `htmltest` complains about this (332 messages!)

Since `htmltest` is going to be running automatically on every build on Netlify, we should really get this solved. Apparently this is something specific to some versions of Ruby, but since we don't have much option on that 🤷‍♂ , we better fix this completely.

@likhobory

**Comment by pgorod** [comment]
@likhobory do you have access to this page?

https://app.netlify.com/sites/suitecrm-docs/deploys/5e5fb9ae88bcea000b54962a

It's a Netlify build log on my personal area. You can see the htmltest output there. If you don't have access, I can paste it all here.

Do you think it's very hard to change all those hashes to lowercase beginnings? You can probably do it from the command-line with `sed`, or with any IDE or text editor that can do find-and-replace-in-files...

**Comment by likhobory** [comment]
Hi @pgorod 

It's not a problem to change all hashes with regexp, the problem is that these lowercase links do not working.  :worried:
Btw, pay attantion -  :toc: on the Russian pages converted to the 'uppercase' links

**Comment by likhobory** [comment]
I intentionally changed 2 hashes to lowercase and I see these 2 errors only.

**lsb_release -a**
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6
Codename:       jessie

**asciidoctor -v**
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

**./bin/htmltest -v**
htmltest 0.12.1
2020-01-25T17:29:58Z

**rm -R public/\* && hugo --enableGitInfo && ./bin/htmltest**
Building sites … WARN 2020/03/05 17:35:41 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
WARN 2020/03/05 17:35:54 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
WARN 2020/03/05 17:36:01 .File.Path on zero object. Wrap it in if or with: {{ with .File }}{{ .Path }}{{ end }}

                   |  EN  |  ES  |  RU
-------------------+------+------+-------
  Pages            |  232 |   42 |  138
  Paginator pages  |    0 |    0 |    0
  Non-page files   |    3 |    1 |    1
  Static files     | 1356 | 1356 | 1356
  Processed images |    0 |    0 |    0
  Aliases          |    1 |    0 |    0
  Sitemaps         |    2 |    1 |    1
  Cleaned          |    0 |    0 |    0

Total in 131832 ms
htmltest started at 05:36:55 on public
\========================================================================
hash does not exist --- ru/admin/advanced-configuration-options/index.html --> ../administration-panel/system/#_восстановление
hash does not exist --- ru/admin/administration-panel/studio/index.html --> ../developer-tools/#_студия
\========================================================================
✘✘✘ failed in 2.536864347s
2 errors in 332 documents

**Comment by pgorod** [comment]
One thing I am still not sure: is this an Asciidoc problem (hashes are generated wrong) or a htmltest problem (gives warning with no good reason)?

I think it's Asciidoc - the hashes should all be lowercase, that's what it does for the other languages, and even in Russian, for all the other words expect the first.

But it must be also creating a mismatch - some other place where it uses the lowercase, even in Russian. If there was no mismatch, then htmltest wouldn't warn. Basically the two things that have to match are the `id` of the header element, and the link to it.

It is possible that other places in the Hugo code are intervening in generating links, etc, so maybe it's not _just_ Asciidoctor causing this... 🤔

**Comment by likhobory** [comment]
> It is possible that other places in the Hugo code are intervening in generating links

I also believe that this is the asciidoc, the hashes should be lowercase in any case, as it described in the oficial asciidoc manual and when I use asciidoc directly to convert some Russian adoc file (without Hugo)  I get the same wrong result.

I watched [this](https://discuss.asciidoctor.org) asciidoc forum, but did not find any description of a similar error...
If it’s not difficult, could you please open the corresponding issue on the developer’s github repository?

In [this](https://github.com/likhobory/SuiteDocs/commits/anch) branch, as an experiment, I added additional anchors in the lowercase, and most likely htmltest will give a log without errors. Perhaps this can be used as a temporary solution, but it looks completely ugly.

**Comment by pgorod** [comment]
Ok, so I'm working on a minimal reproducible example of this issue. I have the following Asciidoc:

```
:toc:

== English section header

Some text.

== Руководство администратора

Some more text.

And now some links to those sections:

<<English section header>>

<<Руководство администратора>>

End of text.
```

I compile this directly with `asciidoctor asciidoctorTest.adoc` which produces the following `asciidoctor asciidoctorTest.html` (this is just a fragment):

```html
<body class="article">
<div id="header">
<div id="toc" class="toc">
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a href="#_english_section_header">English section header</a></li>
<li><a href="#_Руководство_администратора">Руководство администратора</a></li>
</ul>
</div>
</div>
<div id="content">
<div class="sect1">
<h2 id="_english_section_header">English section header</h2>
<div class="sectionbody">
<div class="paragraph">
<p>Some text.</p>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_Руководство_администратора">Руководство администратора</h2>
<div class="sectionbody">
<div class="paragraph">
<p>Some more text.</p>
</div>
<div class="paragraph">
<p>And now some links to those sections:</p>
</div>
<div class="paragraph">
<p><a href="#_english_section_header">English section header</a></p>
</div>
<div class="paragraph">
<p><a href="#_Руководство_администратора">Руководство администратора</a></p>
</div>
<div class="paragraph">
<p>End of text.</p>
</div>
</div>
</div>
</div>
<div id="footer">
<div id="footer-text">
Last updated 2020-03-10 12:50:24 UTC
</div>
</div>
</body>
```

So that works well in Ruby 2.3.8: both the links on the `:toc:` and on the internal section links below appear with lowercase in English, and Uppercase in Russian, but _always consistently_.

It seems that in Ruby 2.6.2 which is what Netlify runs, the Russian links in the `:toc:` are changed to lowercase, and the rest stays the same, provoking the inconsistency and the errors. The internal section links work well.

**Comment by pgorod** [comment]
Ok @likhobory upon further research I don't think there is any problem with Asciidoctor on the newer Rubies. It does change the way it behaves, but it is consistent after all:

--> [Asciidoctor test](https://suitecrm-docs.netlify.com/user/asciidoctortest/#_%D1%80%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE_%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B0)

So my Asciidoctor test runs fine on Ruby 2.6.2, it always uses lowercase, as it should.

The links that are now giving the error are the ones done by ourselves, not the ones generated by Asciidoctor automatically. The errors are in places in the source that look like this:

```
В разделе есть возможность указать рабочие дни и часы работы организации. Указанные параметры  будут учтены при запуске
link:../../../user/advanced-modules/workflow/#_Создание_процесса[Процессов] с установленным параметром запуска *Только $
link:../../../user/core-modules/projects/#_Создание_проекта[Проекта], если в созданном Проекте отмечен параметр *Учитыв$
```
I think that if we correct that source, everything will work well.

**The only thing that is not possible** is to have a site source that works well both for old Rubies, and new Rubies. We have to choose. 

Are you ok with upgrading your Ruby to a newer version? I would have to do the same on my local set-up...

(Before actually upgrading, I will have to solve an unrelated problem: tables of contents are broken in the main Chapters on the new Ruby and Asciidoctor versions, see for example https://suitecrm-docs.netlify.com/user/)

**Comment by pgorod** [comment]
> (Before actually upgrading, I will have to solve an unrelated problem: tables of contents are broken in the main Chapters on the new Ruby and Asciidoctor versions, see for example https://suitecrm-docs.netlify.com/user/)

I have solved ☝️ this problem so now I am just waiting on **your ok** to the following plan:

- we both upgrade our local Ruby
- you edit everything that looks like this in the Russian `link:aaa/bbb/#_Cccc` to become `link:aaa/bbb/#_cccc`
- I move the latest changes from my test site into the official site. 

This should leave us with the latest versions of everything, AND with a clean `htmltest` report automatically created with each deploy. 🎉

**Comment by likhobory** [comment]
Yes, it works fine on Ruby 2.6.2 !

**Comment by pgorod** [comment]
Just a question, which Linux do you use? 

And how do you upgrade or change Ruby versions on it? RVM? rbenv? Simple `apt`?

I've been having a really tough time upgrading :-(

**Comment by likhobory** [comment]
Ubuntu 14.04.6 LTS
I downloaded and compiled exactly the version that you recommended from [here](https://www.ruby-lang.org/en/news/2019/03/13/ruby-2-6-2-released/).

**Comment by pgorod** [comment]
Compile and build... that's very old school ;-)

Ok I think I've finished this. The new site is published, and it passes `hmtltest`, which can now be seen directly in the Netlify deploy log:

https://app.netlify.com/sites/suitedocs/deploys/5e6a2ed22c5511000a8137e6

Please test and tell me if everything is working properly. Once again thanks a lot for your help!

**Comment by likhobory** [comment]
> hat's very old school ;-)
Agree.. ))
Thank you, I'll test it a few hours.

**Comment by likhobory** [comment]
As I understand, this deploy uses the previous Russian files with uppercase letters in the hashes?

**Comment by pgorod** [comment]
Yes, if you mean the deploy I linked above

But later I noticed it those changes were missing and now I believe that `master` has all the latest files, with lowercase hashes.

https://app.netlify.com/sites/suitedocs/deploys/5e6a3bec07e9020008322f45

Live at https://docs.suitecrm.com/

**Comment by likhobory** [comment]
> I believe that master has all the latest files

Yes. Works as expected. 👍
