### ISSUE TITLE
Issue about Page developer/automatedtasks/Sass.adoc

### ISSUE THREAD

**Issue by yuriizee** [salesagility/SuiteDocs#450]
#### Page with Issue
https://docs.suitecrm.com/developer/automatedtasks/sass/

#### What is wrong, less clear, or missing
./vendor/bin/robo build:suite-p --color_scheme=[ColorName]

#### Proposed fixes and/or additions
./vendor/bin/robo build:suite-p --color-scheme=[ColorName]

**Comment by pgorod** [comment]
Sorry, I don't understand what you're asking to be fixed... can you please clarify? Thanks.

**Comment by yuriizee** [comment]
> 
> 
> Sorry, I don't understand what you're asking to be fixed... can you please clarify? Thanks.

--color-scheme and --color-scheme
look this symbol _ must be -

**Comment by pgorod** [comment]
Ok, that wasn't so hard :-)
