### ISSUE TITLE
Issue about Page developer/Introduction.adoc

### ISSUE THREAD

**Issue by mlechner-del** [salesagility/SuiteDocs#455]
#### Page with Issue
https://docs.suitecrm.com/developer/introduction/

#### What is wrong, less clear, or missing
broken link for: In this guide we’ll be using SuiteCRM v7.1.5 which is the latest at time of writing. For up to date versions of the installation instructions see the SuiteCRM wiki at suitecrm.com/wiki/index.php/Installation.

#### Proposed fixes and/or additions
Update link to the correct link.

**Comment by pgorod** [comment]
Fixed in https://github.com/salesagility/SuiteDocs/commit/b7b8132780c999a3592edaef9de4a207b388043e

Thanks!
