### ISSUE TITLE
Russian RAPIRA User Guide

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteDocs#46]
Can I suggest this guide as an official Russian translation?

I would like to convert [Russian RAPIRA application guide](https://github.com/likhobory/SuiteCRM7RU/tree/master/DOCS) from DOCX to ADOC, but its contents are not translated from English verbatim (some sections are translated in more detail, with a lot of images and cross-references, the structure of the table of contents is slightly changed, etc.)

**Comment by pgorod** [comment]
Hi Likhobory!

Have you tried browsing the Spanish site? It was released today. You can have an idea of what the site looks like with a partial translation - only the translated chapters appear on the menu.

You can switch between the several languages using the menu at the bottom of the sidebar, and you are taken to the same, corresponding page, where you were, only in another language. 

This means that keeping the structure and file names is essential. So any Russian manual that we include needs to have the same chapters, the same file names (with just an added ".ru" before the extension.

The smaller differences in the text, and the different screenshots, are not a problem, although I want to keep all the different languages parallel to avoid confusion, and to keep "translated versions of the site", not "different versions of the site".

Can you adapt your manual like I am describing? If there is something additional that you felt was important to document, maybe we can also add it to the English version.

**Comment by likhobory** [comment]
> So any Russian manual that we include needs to have the same chapters, the same file names.
It's not a problem, But the chapers content may be slightly different from the original english version. For example the Google maps chapters content was got from JJWDesign

**Comment by pgorod** [comment]
Ok. You might want to follow this tutorial so you can try things on your own computer:

https://docs.suitecrm.com/community/contributing-to-docs/local-setup/

See [this note](https://github.com/salesagility/SuiteDocs/issues/7#issuecomment-370143282) for some other instructions about how to translate the menus.

Note that I can't promise we'll add the Russian guide right away, I'll have to ask other people in SA what their plans are for this. But am fairly confident that we can open this up to contributions in many languages soon... fingers crossed.

**Comment by likhobory** [comment]
Thanks, in any case the Russian documentation will be located [here](https://github.com/likhobory/SuiteAsciiDocRU). 
All images from ver. 7.8 will be updated.

**Comment by pgorod** [comment]
@likhobory I think we're almost ready to advance with the Russian area of the documentation site. Note that this will be putting a lot of trust in you, since we can't evaluate how good Russian content is :-)

Have you had a chance to set up a local environment with Hugo so you can work on the site? Tell me if you need any help with that.

Today I will try to advance the Homepage to make it translatable, so that the Spanish site has a translation. Keep an eye on this file, which will be growing a lot today, and you (or someone willing to help you) will need to do it for Russian when you can:

`https://github.com/salesagility/SuiteDocs/blob/master/i18n/en.toml`

**Comment by likhobory** [comment]
Thanks Pedro!

Yes, I'm translating on the local server without problems.
I have a few questions about the strange behavior of asciidoctor when it processing some tags, but it's not critical and I'll ask them later in another issue.

**Comment by likhobory** [comment]
About ru.toml
You can use [this](https://github.com/likhobory/SuiteAsciiDocRU/blob/master/i18n/ru.toml) one.

**Comment by pgorod** [comment]
I notice you have a license text there.

Would you be ok with contributing your text into our site, and with our current license statement at the bottom of every screen, which reads `Content is available under GNU Free Documentation License 1.3 or later unless otherwise noted.`?

**Comment by likhobory** [comment]
I use the same [GNU Free Documentation License 1.3](https://github.com/likhobory/SuiteAsciiDocRU/blob/master/LICENSE.md), so I do not see any problem :)

**Comment by pgorod** [comment]
@likhobory what do you think about Technical blog translation?

Currently we have a good number of articles ready, you can see them here https://github.com/salesagility/SuiteDocs/tree/master/_source/future-blog-posts and we have more we can grab from some Blogs out there that gave us permission.

Do you think there is interest (and availablity) in translating all of it? 

Should the Russian blog show all articles, some in English, some in Russian (if they are translated), or should it show only the translated ones?

**Comment by likhobory** [comment]
IMHO this articles do not need a translation and should be published in the Russian blog  "AS IS". 
But if someone wants to translate them later - why not?

**Comment by pgorod** [comment]
Ok, that's helpful. I just need to decide how make the Blog post list work on the international sites, and according to your suggestion (which I agree) way I can use this logic:

- make it list the more recent posts, 
- use a translated post if available
- use English post if not

**Comment by likhobory** [comment]
Conversion is complete. 

* \user\Modules\Email Settings.adoc
* \user\Modules\PasswordManagement.adoc

I recommend to move the contents of these files to the [Admin Panel folder](https://github.com/likhobory/SuiteAsciiDocRU/tree/master/content/admin/Administration%20Panel) to System.adoc and Users.adoc files as we discussed in #57.

**Comment by pgorod** [comment]
I just merged the Russian guide into master! You can browse it live.

Thanks for all your work!

**Comment by likhobory** [comment]
Suggestion.
It would be nice if the "Latest Posts From our technical blog" frame were filled with both Russian and English articles. Now it's empty on Russian page and it does not look good.

**Comment by pgorod** [comment]
You're right, I know... I was hoping @DirtyF could give me a hand with that, if he knows the answer. I've looked at the code but I don't see any place where it's selecting articles to list by language... ?
