### ISSUE TITLE
Issue about Page community/_index.en.adoc

### ISSUE THREAD

**Issue by russellwilmarth** [salesagility/SuiteDocs#469]
Could not connect to the database. Please refer to suitecrm.log for details (0).
Fatal error: Uncaught Exception: Could not connect to the database. Please refer to suitecrm.log for details (0). in /var/www/html/suitecrm/include/utils.php:1884 Stack trace: #0 /var/www/html/suitecrm/include/database/MysqliManager.php(327): sugar_die('Could not conne...') #1 /var/www/html/suitecrm/include/database/DBManagerFactory.php(150): MysqliManager->connect(Array, true) #2 /var/www/html/suitecrm/include/entryPoint.php(182): DBManagerFactory::getInstance() #3 /var/www/html/suitecrm/index.php(47): require_once('/var/www/html/s...') #4 {main} thrown in /var/www/html/suitecrm/include/utils.php on line 1884

**Comment by pgorod** [comment]
Hi

I see you've opened a thread about this on the correct place, the Forums: https://community.suitecrm.com/t/getting-error-on-install/74426

Can you please close this issue here? Thanks
