### ISSUE TITLE
Issue about Page user/Advanced Modules/Cases with Portal.adoc

### ISSUE THREAD

**Issue by TheLimey** [salesagility/SuiteDocs#47]
#### Page with Issue
https://docs.suitecrm.com/user/advanced-modules/cases-with-portal/

#### What is wrong, less clear, or missing
This sentence instructs the reader to install the "Joomla AOP component", however give no instructions on how to do that beyond telling them the use the "Joomla Extension Manger". Maybe, it's so simple it's not worth explaining how, but I cannot even find the "Joomla Extension Manager" in my SuiteCRM.

> To install the Joomla AOP component, use the Joomla Extension Manager

#### Proposed fixes and/or additions
More information, or a link to full instructions would be really helpful. =)

**Comment by likhobory** [comment]
>  but I cannot even find the "Joomla Extension Manager" in my SuiteCRM.

@TheLimey 
You should use  "Joomla Extension Manager" in your Joomla instance, not in your SuiteCRM.

**Comment by pgorod** [comment]
We could, of course, improve these instructions, they're quite old and maybe outdated. I think there's an installer of the AOP Portal that can be downloaded from the SuiteCRM site, and if I'm not mistaken it does all Joomla configuration by itself, so you don't even have to go in "Joomla Extension Manager".

Or am I wrong?

**Comment by pgorod** [comment]
I made a few changes, tell me if there's anything more to improve. Thanks

https://github.com/salesagility/SuiteDocs/commit/c4e8787e5a4f4e3ce4c0ec5b72324051762474af
