### ISSUE TITLE
Can't add Inter-document Cross Reference

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteDocs#51]
There is no problem with internal cross references, but when I try to add some references  to another document, for example from _index.ru.adoc to User Interface.ru.adoc:
`<<../User Interface.ru.adoc#Some section,Some section>>`
I've got this wrong link
> . . . /user/introduction/User%20Interface.ru.html#Some%20section

insted of
>. . . /user/introduction/user-interface.ru/#_some_section

Upd: Now I use `link:` notation, although it's much less convenient.

**Environment:**
Debian 9.4
hugo 0.37
Asciidoctor 1.5.4

**Comment by pgorod** [comment]
I also could never get that `<< ... >>` syntax to work except for internal section links.

Use this syntax instead:

`link:/user/introduction/user-interface.ru/#_some_section[Link text]`

Thanks!

**Comment by likhobory** [comment]
It's a pity, thanks.
