### ISSUE TITLE
Issue about Page user/modules/Themes.adoc

### ISSUE THREAD

**Issue by Adanck** [salesagility/SuiteDocs#511]
#### When changing the theme and choosing something other than Dawn, the theme does not load well, and all the labels appear aligned to the left

How can i fix this
I chose the theme Night and it doesn't work

**Comment by pgorod** [comment]
You should be asking about this in the Forums:

https://community.suitecrm.com/

This here is for documentation updates, please close this issue and ask in the link I gave above. Thanks.
