### ISSUE TITLE
Netlify Previews gone?

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteDocs#513]
Regarding the Docs site deployment, lately I can't find the link to take me to the Deployment previews on Netlify.

These used to appear in the PR's, near the bottom, and were a great way to provisionally browse the site with the new PR included and see how it renders.

Maybe something got de-configured. Tell me if you need help getting it back.

There are some very [cool new features on Netlify previews](https://www.netlify.com/blog/2021/05/19/next-generation-deploy-previews-plus-netlify-acquires-featurepeek/) which I'd like to try.

**Comment by mattlorimer** [comment]
not seen them in the PR's lately, but you can manually link to them here https://app.netlify.com/sites/suitedocs/deploys

Netlify have requested additional permission for the GitHub Repo in the last day, which we have now updated, which is likely related to new features but we have not review them specifically yet

**Comment by samus-aran** [comment]
My lastest PR did get a preview built (failed but that is a different issue). I dunno if that was a cause of whatever happened in the past few days or when someone reviews a PR.

**Comment by pgorod** [comment]
Was that a Deploy preview seen from the Netlify site, or a link here on our GitHub to access the previewed site directly? I can't find this last one in your PR...

**Comment by jack7anderson7** [comment]
Hi @pgorod,

We will close this as it appears to no longer be an issue.

Thanks,
Jack
