### ISSUE TITLE
Issue about Page admin/administration-panel/Google Sync.adoc

### ISSUE THREAD

**Issue by fredjohnston** [salesagility/SuiteDocs#523]

**Comment by fredjohnston** [comment]
Getting attached message when I try to authorize using the steps provided.  Some steps are confusing (Google probably added / changed).  There's mention of "scopes" etc... not sure... Also, it says to contact the developer, and lists MY email address... which doesn't look right)...
![Screen Shot 2021-06-06 at 8 03 17 PM](https://user-images.githubusercontent.com/28265553/120944527-fe956e00-c702-11eb-880b-156e4292e675.png)

**Comment by pgorod** [comment]
Hi

I think you want to ask about this in the Forums. This site here is about user-contributed improvements to the Documentation.

https://community.suitecrm.com/
