### ISSUE TITLE
Issue about Page developer/api/Developer-setup-guide/Customization.adoc

### ISSUE THREAD

**Issue by Sshahar** [salesagility/SuiteDocs#524]
#### Page with Issue
https://docs.suitecrm.com/developer/api/developer-setup-guide/customization/#_customization

#### What is wrong, less clear, or missing
How do I install slim framework on ucs? for some reason I cannot connect to the server from the host of the vm. even though testing on Ubuntu Server I had no problems.

#### Proposed fixes and/or additions
Provide info on how to add API server to the Univention OS.

**Comment by pgorod** [comment]
I believe that is too specific for this Docs page, you're probably better off asking about this in the Forums, perhaps someone else has experience with the UCS install.

**Comment by jack7anderson7** [comment]
Hi @Sshahar,

We agree with @pgorod, we believe that this is too specific for the docs page and would be a more suited question for the forums.

We will close this issue for now.

Thanks,
Jack
