### ISSUE TITLE
Issue about Page user/_index.ru.adoc

### ISSUE THREAD

**Issue by yaroslaw74** [salesagility/SuiteDocs#556]
#### Page with Issue
Add outgoing mail server
https://crm.concombit.com/#/outbound-email-accounts/edit?return_module=OutboundEmailAccounts&return_action=DetailView

#### What is wrong, less clear, or missing
![image](https://user-images.githubusercontent.com/92985624/144027180-187af576-cdd5-4ce6-8cdd-3fc1a0620e0e.png)

**Comment by mattlorimer** [comment]
this is not am issue relate to the documentation site, suggest you log your issue in the support forum -> https://community.suitecrm.com/
