### ISSUE TITLE
Install Not working 

### ISSUE THREAD

**Issue by wanesmith** [salesagility/SuiteDocs#558]
#### Page with Issue
install
Centos 7/Maria DB/ 
#### What is wrong, less clear, or missing
try to install the install page not showing . Install by command line says successful but still get blank page

<!DOCTYPE html><html lang="en"><head>
    <meta charset="utf-8">
    <title>SuiteCRM</title>
    <base href="">

    <meta http-equiv="cache-control" content="no-cache, must-revalidate, post-check=0, pre-check=0">
    <meta http-equiv="expires" content="0">
    <meta http-equiv="pragma" content="no-cache">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">

    <link rel="manifest" href="site.webmanifest">
    <link rel="icon" type="image/x-icon" href="dist/themes/suite8/images/favicon.ico">
<style>:root{--blue:#007bff;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#dc3545;--orange:#fd7e14;--yellow:#ffc107;--green:#28a745;--teal:#20c997;--cyan:#17a2b8;--white:#fff;--gray:#6c757d;--gray-dark:#343a40;--primary:#007bff;--secondary:#6c757d;--success:#28a745;--info:#17a2b8;--warning:#ffc107;--danger:#dc3545;--light:#f8f9fa;--dark:#343a40;--breakpoint-xs:0;--breakpoint-sm:576px;--breakpoint-md:768px;--breakpoint-lg:992px;--breakpoint-xl:1200px;--font-family-sans-serif:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";--font-family-monospace:SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;}*,:after,:before{box-sizing:border-box;}html{font-family:sans-serif;line-height:1.15;-webkit-text-size-adjust:100%;-webkit-tap-highlight-color:transparent;}body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;font-size:1rem;font-weight:400;line-height:1.5;color:#212529;text-align:left;background-color:#fff;}body{height:100%;margin:0;padding:0;border:none;background:#f5f5f5;}</style><link rel="stylesheet" href="dist/styles.5806247e63e952e4fef7.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="dist/styles.5806247e63e952e4fef7.css"></noscript></head>

<body>
<app-root></app-root>
<script src="dist/polyfills-es5.bd572d5a52462b4db2e4.js" nomodule defer></script><script src="dist/polyfills-es2015.b81ce80777ba591aef43.js" type="module"></script><script src="dist/main-es2015.4f73151df6d41fcd807b.js" type="module"></script><script src="dist/main-es5.4f73151df6d41fcd807b.js" nomodule defer></script>

</body></html>

**Comment by mattlorimer** [comment]
We are closing this issue as it does not appear to be relevant to the documentation repo, if you feel otherwise please provide more information and we can look at reopening this issue 

Otherwise I would suggest you use the [community forum](https://community.suitecrm.com/) to get help with your issue or if you feel this is a core issue and you can provide the relevant detail  you can report it the relevant project repo, [SuiteCRM 8+](https://github.com/salesagility/SuiteCRM-Core) or [SuiteCRM 7](https://github.com/salesagility/SuiteCRM)
