### ISSUE TITLE
Administrator Guide chapters

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteDocs#57]
Do you have a plan to publish a full administrator's guide?
If so, it would be nice to know the chapters structure.

At the moment, the Russian Administrator guide consists of the following chapters (as on the administration page):

Пользователи	/ Users
Система	/ System
Администрирование электронной почты	/ Email
Инструментарий разработчика	/ Developer Tools
Настройка портала / AOP Settings
Настройка модулей продаж	/ AOS Settings
Настройка полнотекстового поиска	/ AOD Settings
Настройка графика работы	/ Business hours
Карты Google	/ Google Maps
Управление версиями	/ Releases
Управление перечнем сотрудников	/ Employee Records
Настройка дополнительных параметров	/ Advanced Configuration Options

(As you can see the Advanced OpenAdmin section has been divided into several separate chapters for greater convenience.)
Maybe we can use this structure (or part of it) in the future translation?

**Comment by CBeechey** [comment]
Yes, we are planning to do this too. The structure is most likely to follow the sections on the Administration page, just as you suggest, and we will let you know once this has been finalised.

**Comment by likhobory** [comment]
> Управление версиями / Releases

In order to avoid conflict with existing file Releases.ru.adoc this file has been renamed to "Releases Settings.ru.adoc"

**Comment by pgorod** [comment]
@likhobory what is the status on this one, after the recent merges?

Are we even on English and Russian, with the same files, on Admin guide?

**Comment by likhobory** [comment]
Partially. I propose to add English versions of these files:

- https://github.com/salesagility/SuiteDocs/blob/master/content/admin/Advanced%20Configuration%20Options.ru.adoc

- https://github.com/salesagility/SuiteDocs/blob/master/content/admin/administration-panel/Google%20Maps.ru.adoc

- https://github.com/salesagility/SuiteDocs/blob/master/content/admin/administration-panel/Bugs.ru.adoc

- https://github.com/salesagility/SuiteDocs/blob/master/content/admin/administration-panel/Employee%20Records.ru.adoc
