### ISSUE TITLE
 User Guide chapters 

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteDocs#58]
The description of the following modules are not available in the English guide, but present in the Russian guide:

- PDF Templates / PDF-шаблоны
- Knowledge Base / База знаний
- Spots / Сводки
- Employees / Сотрудники
- Errors / Ошибки

Do you have a plan to add them (or part of them) into English user guide? 
If so, how that files will be named and in which section they will be located?
Weight for each file?

**Comment by pgorod** [comment]
@CBeechey Claire what do you think about this?

**Comment by CBeechey** [comment]
Yes, we are intending to add documentation for these modules to the English user guide. Following current conventions the file names will be the same as the module names. PDF Templates and Knowledge Base will be in the Advanced Modules section, and the others in Core Modules.

**Comment by likhobory** [comment]
Thanks.

**Comment by jack7anderson7** [comment]
@likhobory, What is the english translation for Контрагенты as there isn't a "counterparties" in Suite

**Comment by likhobory** [comment]
@jack7anderson7 

Контрагенты->Accounts

**Comment by pgorod** [comment]
Thanks for all your hard work guys, I think this is now complete 🥇

**Comment by likhobory** [comment]
> I think this is now complete

Almost, see also https://github.com/salesagility/SuiteDocs/issues/138#issuecomment-420233016 ;)

**Comment by pgorod** [comment]
Ok, but that one has an open Issue specific for it, so I guess it won't be forgotten :-)
