### ISSUE TITLE
Issue about Page developer/API/version-8/JSON-API.adoc

### ISSUE THREAD

**Issue by patcarter883** [salesagility/SuiteDocs#59]
#### Page with Issue
https://docs.suitecrm.com/developer/api/version-8/json-api/#_module_record

#### What is wrong, less clear, or missing
Method for update is incorrect.

#### Proposed fixes and/or additions
Change PUT to PATCH

**Comment by CBeechey** [comment]
Thanks @patcarter883, this has now been updated.
