### ISSUE TITLE
Improve use of Asciidoc elements in current content

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteDocs#6]
Make an evaluation of what kinds of stuff we have in the current User and Developer Guides: 

- Admonitions (note, tip, warning, etc)
- Tables
- Captions 
- etc

Then study the Asciidoc tutorials (that's our markup language!) and figure out what we can use to get better looking content.

**Comment by pgorod** [comment]
We can change the admonitions (info, tip, warning, etc.) to these nice boxes our Theme includes:

https://themes.gohugo.io/theme/hugo-theme-learn/en/shortcodes/notice/

**Comment by pgorod** [comment]
We should change the code block captions. Now they look like this:

![image](https://user-images.githubusercontent.com/15945027/33674178-aa17cf0e-daa6-11e7-8a19-589d105a0da3.png)

We should change the source Asciidoc to **use the "starting dot"** to make it a title, and **remove the extra newlines**:

```
.Example 3.1: Creating a new Bean using the BeanFactory
[source,php]
1 $bean = BeanFactory::newBean('<TheModule>');
2 //For example a new account bean:
3 $accountBean = BeanFactory::newBean('Accounts');
```

So this will cause a specific class to render:
```html 
<div class="listingblock">
<div class="title">Example 3.1: Creating a new Bean using the BeanFactory
</div>
```

And this way we can style it more precisely and consistently.

**Comment by pgorod** [comment]
@FinnT97 should we consider this done?

**Comment by FinnT97** [comment]
Yeah I would say so, we've added a lot of pretty cool features!
