### ISSUE TITLE
Issue about Page user/introduction/User Interface/Record Management.adoc

### ISSUE THREAD

**Issue by ColLemaiyan** [salesagility/SuiteDocs#608]

**Comment by serhiisamko091184** [comment]
Hello @ColLemaiyan, 

thanks for your interest in contributing to the SuiteCRM project, 

could you please update the issue with the information on what needs to be fixed?  

Thanks a lot in advance! 

Regards, 
Serhii

**Comment by serhiisamko091184** [comment]
Hello @ColLemaiyan,

one more time thank you for the issue raised.
I checked the page, mentioned in the issue's title, several times. I'm afraid I haven't managed to identify possible problems.    
I'm closing this issue, and I hope you can reopen it and update it when it’s appropriate for you.    
Thank you very much! 

Regards,
Serhii
