### ISSUE TITLE
Issue about Page developer/API/API-4_1.adoc

### ISSUE THREAD

**Issue by nextgeni-shakeeb** [salesagility/SuiteDocs#61]
#### Page with Issue

On this page: https://docs.suitecrm.com/developer/api/api-4_1/

#### What is wrong, less clear, or missing
The link is broken: 

> For a full list of API methods and their arguments see Appendix B.

 I unable to see module list

**Comment by CBeechey** [comment]
@nextgeni-shakeeb thank you for notifying us - the broken links to the appendix have now been fixed.
