### ISSUE TITLE
Issue about Page user/advanced-modules/PDFTemplates.adoc

### ISSUE THREAD

**Issue by Hiranyaloka** [salesagility/SuiteDocs#610]
#### Page with Issue

https://docs.suitecrm.com/user/advanced-modules/pdftemplates/
#### What is wrong, less clear, or missing
In the following example, the item Addresses is added to the list.
#### Proposed fixes and/or additions
In the following example, the item "Prospects" is added to the list.

**Comment by likhobory** [comment]
Yes, it was a direct translation from the Russian page, it should be "In the following example, the item **Prospects** is added to the list."

**Comment by Hiranyaloka** [comment]
Yes, "Prospects" would be consistent with the image. "Targets" is the name of the core module, but that would involve changing the text AND the image.
