### ISSUE TITLE
Make Homepage translatable

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteDocs#62]
Our Home page needs to be edited so that every string is looking for a localized version.

See an example of these changes here:
https://github.com/salesagility/SuiteDocs/commit/81743e5f4ea8f1a8e02f51cd1f09f1f5083dee6e

Note that there is currently a bug in our Theme that makes the translated home page look broken, but this shouldn't stop us from advancing this Issue here.

(I've reported that bug here https://github.com/matcornic/hugo-theme-learn/issues/140)

All the other CTA's ("calls to action") in the Homepage need to get that `{{ T "label" }} tag added, and the corresponding entry made on the `en.toml` file. Then the translators can add them also in other files like `es.toml`. The commit I linked above should make this easy to understand, hopefully.

**Comment by pgorod** [comment]
Ok the "theme bug" was not a theme bug, now it's fixed thanks to @DirtyF.

So the Spanish Homepage is now rendering correctly, and all it needs is some more Spanish in it! :-)

**Comment by CBeechey** [comment]
changes made - pr #77

**Comment by pgorod** [comment]
@Abuelodelanada if you can help with the translation of the Spanish Homepage, it is now ready to be translated.

You just need to edit `i18n/es.toml`, the strings are all there now. Thanks!

**Comment by Abuelodelanada** [comment]
@pgorod I'll ask someone here in gcoop to start translating.

**Comment by likhobory** [comment]
@pgorod @CBeechey 

- Some messages are hard coded:
https://github.com/salesagility/SuiteDocs/blob/master/layouts/partials/recently-edited.html#L1-L2

- Translation is missing for {{ T "FromTechnicalBlog" }}:
https://github.com/salesagility/SuiteDocs/blob/master/layouts/partials/last-blog-posts.html#L2

**Comment by CBeechey** [comment]
(Label translation for FromTechnicalBlog added in previous commit)
Labels added for headings in layouts/partials/recently-edited.html pr #87

**Comment by pgorod** [comment]
@Abuelodelanada how is this progressing? I am afraid we have a half-translated Spanish homepage, it makes us look bad... :-( I was hoping we could at least fix the Homepage, even if then the rest of the translations proceed slower.

**Comment by Abuelodelanada** [comment]
Hi @pgorod we are in the middle of a mess with some projects and we could not take the time to translate. I hope in the following days we will free to do that.

**Comment by pgorod** [comment]
@Abuelodelanada I went ahead and translated these strings so the Spanish homepage would look decent. If you can later have a look and suggest improvements that would be great. Just tell me here what you think should be changed, so it doesn't take up too much of your time.

We will be launching the Russian version of the site soon, and it be published on our Facebook, Twitter, etc., attracting attention, so I want the Spanish homepage to look good! :-)

**Comment by Abuelodelanada** [comment]
Hi @pgorod looks good!

may be we can add a message saying: 
"Estamos trabajando en la traducción de este sitio al Castellano. Si querés ayudarnos, hacé click aqui." (With a link to: https://docs.suitecrm.com/es/community/contributing-to-docs/simple-edit)


We have a person translating the User Guide right now, and another person translating the Developer guide (https://github.com/gcoop-libre/SuiteDocs/commits/Developer_es)

For the developer guide, would you like a PR right now? o would you prefer we finish it?

**Comment by Abuelodelanada** [comment]
I would put it below:

"Documentación SuiteCRM"

**Comment by pgorod** [comment]
Hi @Abuelodelanada it seems the translation is stalled for now... maybe it's a good time to make a Pull Request with the files already translated?

**Comment by Abuelodelanada** [comment]
Hi @pgorod 

yes, we are with a lot of work ... I'll tell the guys that were translating to make a PR.

**Comment by pgorod** [comment]
I believe this is done, so I am closing. If not, them please point me exactly to a non-translatable string in the main Docs UI.
