### ISSUE TITLE
Issue about Page admin/administration-panel/Google Sync.adoc

### ISSUE THREAD

**Issue by Hammerill** [salesagility/SuiteDocs#639]
#### Page with Issue
https://docs.suitecrm.com/admin/administration-panel/google-sync/

#### What is wrong, less clear, or missing
Hello, I just wanted to know how to delete all the saved tokens in order to "revert" the changes we made.

This guide clearly explains how to add Google sync and use it, but I couldn't find online any doc that would explain how do we cancel it.
For example, we need to use another Google Cloud token, but reuploading and reauthorizing it raises the `ERR_CONNECTION_REFUSED`.
Maybe, it would be more stable if this was a clear authorization, not a "re"-authorization.

#### Proposed fixes and/or additions
Please add a subsection to this guide explaining what files one has to delete in order to remove any trace of the Google sync.

**Comment by pgorod** [comment]
Hi.

It's possible (or even, likely) that nobody knows how to do this, so it's not easy to just start writing docs for it.

If you raised this in the Forums instead, I believe you would have a better chance of getting attention.

**Comment by Hammerill** [comment]
After this [research](https://community.suitecrm.com/t/how-to-remove-google-calendar-sync/92029/3), the solution we have is:
- Admin has to delete the Google Cloud token line in `/config_override.php`. It begins with `$sugar_config['google_auth_json'] = `.
- In order to reset Google authorization, user can reset their personal settings. It _might_ be excessive if the token is already deleted from the admin config.

The `ERR_CONNECTION_REFUSED` was caused by the wrong server redirection URI I forgot to update in our Google Cloud token. Setting it to a correct URI and re-adding it solved our problem.
