### ISSUE TITLE
Issue about Page developer/API/API-4_1.adoc

### ISSUE THREAD

**Issue by gitbnw** [salesagility/SuiteDocs#64]
#### Page with Issue

https://docs.suitecrm.com/developer/api/api-4_1/

#### What is wrong, less clear, or missing
The link in this warning message is broken:
This documentation pertains to SuiteCRM versions up to v.7.9.x. Since SuiteCRM version 7.10, [a brand new v8 REST API](https://docs.suitecrm.com/developer/api/api-8) is available.

#### Proposed fixes and/or additions
Remove: https://docs.suitecrm.com/developer/api/api-8
Add: https://docs.suitecrm.com/developer/api/version-8/

**Comment by CBeechey** [comment]
thanks @gitbnw, this link has now been updated
