### ISSUE TITLE
Issue about Page 8.x/admin/releases/8.2/_index.en.adoc

### ISSUE THREAD

**Issue by kale1d0code** [salesagility/SuiteDocs#652]
#### Page with Issue

https://docs.suitecrm.com/8.x/admin/releases/8.2/
#### What is wrong, less clear, or missing
Download Link doesn't work. Takes me to https://suitecrm.com/download/
#### Proposed fixes and/or additions
should start downloading 8.2.4 or show a page with links to 8.2.4 downloads / migrations

**Comment by jack7anderson7** [comment]
Hi @kale1d0code 

Thank you for your contribution!
We have updated this to point to the correct place. I will close this now

Thanks, 
Jack
