### ISSUE TITLE
Advance Search in Meetings module, filtered by starting date not working

### ISSUE THREAD

**Issue by omidpand** [salesagility/SuiteDocs#657]
#### Page with Issue
http://192.168.xxx.xxx/index.php?module=Meetings&action=index

#### What is wrong, less clear, or missing
In the advanced search, I set the start date Equals to 05/19/2024  (or any other date) and hit the search button, but the displayed result is always related to today's date. (2024/05/21)
SuiteCRM Version is:
Version 7.14.3
Sugar Version 6.5.25 (Build 344)

**Comment by omidpand** [comment]
Any suggestion?

**Comment by pgorod** [comment]
Hi

You're asking in the wrong place.

This here is for people to contribute changes to the documentation, Wikipedia-style.

You're probably looking for help, I suggest you post in the community forums instead.

See you there

**Comment by serhiisamko091184** [comment]
Hello @omidpand,

thanks for your interest in our project, 

if you have discovered an issue, please, raise it here for SuiteCRM 7.X.X:
https://github.com/salesagility/SuiteCRM/issues
or here for SuiteCRM 8.X.X: 
https://github.com/salesagility/SuiteCRM-Core/issues

If you are looking for support and more information, here are useful links: 
1) documentation: https://docs.suitecrm.com/
2) community forum for more info: https://community.suitecrm.com/

Thanks a lot! 

Regards,
Serhii
