### ISSUE TITLE
How to set email account of SuiteCRM 8.7?

### ISSUE THREAD

**Issue by 5270d** [salesagility/SuiteDocs#669]
Version: 8.7

I can send a test email after I set my email account. And the receiver email account
can also receive the test email.

"This email was sent in order to test the outgoing mail server information provided in the SuiteCRM application. A successful receipt of this email indicates that the outgoing mail server information provided is valid."

When I select a contacts email to use my administrator email account to send an
email, the window will show below wrong content. Who can help me to solve this 
wrong? Thanks in advance.

"Error Sending Email. Please contact your administrator for assistance."

The suitecrm.log is the following,

"Fri Oct 18 04:20:21 2024 [7647][1][FATAL] log call at: modules/EmailMan/tpls/config.tpl - styleChecked is not set
Fri Oct 18 04:35:59 2024 [7643][1][SECURITY] Email Error: Not authorized to use Outbound Account "system"
Fri Oct 18 04:35:59 2024 [7643][1][SECURITY] User M*Y attempted to send an email using incorrect email account settings in which they do not have access to."

I can't also find the solutions from suitecrm user guide. And I don't how to set Inbound
and Outbound account.

In addition, I found one bug from suitecrm 8.7.
When I set a correct time zone, such as Asia/Shanghai(GMT +8:00). When I logout and login with administrator again, the time zone will recover to original zero time zone -
UTC (GMT +0:00).

**Comment by pgorod** [comment]
I think this kind of question is more suitable to the Community Forums:

https://community.suitecrm.com/

Please close this issue here and ask there. Thanks!
