### ISSUE TITLE
Issue about Page admin/Installation Guide/Downloading 

### ISSUE THREAD

**Issue by rhinostrehorse** [salesagility/SuiteDocs#68]
#### What is wrong, less clear, or missing

Guide is confusing when it comes to setting permissions. One line says apachegroup and another says www-data. Then the same a.b.c is used for more than one thing. How is anyone supposed to get it right?

**Comment by pgorod** [comment]
I made a few improvements. 
https://github.com/salesagility/SuiteDocs/commit/915a14a141ef1ff88f687e6ecb59c198847618f0

However that guide needs a more complete re-write... and you are right, all those nested indents with "a, b, c" are confusing.

**Comment by rhinostrehorse** [comment]
Hi

 

Thanks

 

One thing

 

"sudo chmod -R 775 cache custom modules themes data upload config_override.php"

 

there is no file called "config_override.php" in the SuiteCRM root.

 

Regards 
Jon Eyre

                      



Jon Eyre | Technical | MTechSA (Pty) Ltd | Voice +27 <tel:%2B27%C2%A011%C2%A0801%209300>  11 801 9300 | Fax General  <mailto:+27%2011 796%200411> +27 11 796 0411 |  <mailto:jon.eyre@mtechsa.co.za> jon.eyre@mtechsa.co.za

(Pty) Ltd is a Level 3 BBBEE Contributor

**Comment by rhinostrehorse** [comment]
Hi

Thanks

One thing

"sudo chmod -R 775 cache custom modules themes data upload config_override.php"

there is no file called "config_override.php" in the SuiteCRM root.

**Comment by pgorod** [comment]
I fixed that also. Thanks

I'll leave this Issue open until we get a chance to re-write that guide.

**Comment by pgorod** [comment]
Even though I still have plans for rewriting some of this content, I'm closing the issue since I am planning my work in a different way, having many open Issues with fragmented ideas doesn't help. Thanks for your suggestions!
