### ISSUE TITLE
Issue about Page admin/Installation Guide/_index.en.adoc

### ISSUE THREAD

**Issue by tdseward** [salesagility/SuiteDocs#75]
#### Page with Issue
https://docs.suitecrm.com/admin/installation-guide/

#### What is wrong, less clear, or missing

See the latest release notes for SuiteCRM here.  The Click "here" is not a current link.

#### Proposed fixes and/or additions

Correct current link to the proper release notes location i.e.  https://docs.suitecrm.com/admin/releases/

**Comment by CBeechey** [comment]
@tdseward Thanks for bringing that to our attention, the link to the release notes has now been fixed.
