### ISSUE TITLE
Security Suite: additional non-existent features in the documentation

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteDocs#86]
From Security Suite (Groups).adoc

Quote1: 

>**Shared Calendar - Hide Restricted**
By default users can see when other users are busy on the Shared Calendar. Even if you doesn’t have rights to the meeting, call, etc. It will display on the calendar, but you cannot view more details unless you have rights to that specific calendar item. By setting this option you cannot see these items on the Shared Calendar; only items that you actually has rights to.

Quote2: 
>**Groups Setup**
There are 3 key steps to setting up Groups so that you work correctly....
 **You can use the Mass Assign on the List View to do this**.

It would be nice to use Shared Calendar restriction and Group Mass Update, but now these features are not present in the actual SuiteCRM version.

**Comment by CBeechey** [comment]
@likhobory Thanks for highlighting these inaccuracies in the documentation. We are in the process of updating the security groups documentation as part of the new Administration panel documentation.

**Comment by pgorod** [comment]
@likhobory what do you mean that Group Mass Update is not present in current SuiteCRM version? I just checked my 7.10.4 and it's there. To my knowledge, it was always there, it was never removed...

**Comment by likhobory** [comment]
@pgorod 
hmm, correct me if I'm wrong, but I can't update some group on the List View for several accounts:

![image](https://user-images.githubusercontent.com/5983672/39356042-b3938d3a-4a17-11e8-9e7b-e8b1a486ae05.png)

**Comment by pgorod** [comment]
I can. I'm on 7.10.4, with Admin user:

![image](https://user-images.githubusercontent.com/15945027/39356987-5ee065e6-4a09-11e8-97c9-ec1bdedf7c22.png)

I always have that section on the bottom showing (even without selecting `Mass update`)

**Comment by likhobory** [comment]
I'm on 7.10.4, with Admin user, but I can't. (with selecting Mass update)
The same result after QRR.

**Comment by pgorod** [comment]
That sounds like a bug,m or an issue with your installation.

Maybe this will help, or you can ask there...
https://www.sugaroutfitters.com/support/securitysuite/151

**Comment by likhobory** [comment]
Thanks, you've right, the file custom/modules/logic_hooks.php is missing.
Now it works as expected and issue with "Quote1" is resolved.

<offtop>
It's not a question for this topic but it would be nice to have the ability to assign SEVERAL groups to selected records (multiselect) on Mass Update panel. 
</offtop>

**Comment by pgorod** [comment]
Good. You probably mean "Quote 2", right?

**Comment by pgorod** [comment]
About Quote 1, the Calendar issue, maybe this should be handled first as a Product issue (on the main repo): check if this functionality was removed on purpose (I doubt it), and whether it's just a specific issue with your installation. Then if it's really gone, we can adjust the Docs.

**Comment by likhobory** [comment]
>You probably mean "Quote 2", right?

Yes :)

Do you have the 'Shared Calendar - Hide Restricted' option on your installation?

**Comment by CBeechey** [comment]
I believe that the 'Shared Calendar - Hide Restricted' feature is only available if you have the full Security Suite package installed - store.suitecrm.com/addons/securitysuite, so I think it has been included in the SuiteCRM documentation by error.

**Comment by pgorod** [comment]
I removed the paragraph. Closing.
