### ISSUE TITLE
Issue about Page developer/Metadata.adoc

### ISSUE THREAD

**Issue by frnklnrd** [salesagility/SuiteDocs#92]
#### Page with Issue

https://docs.suitecrm.com/developer/metadata/

#### What is wrong, less clear, or missing

In "Customising" area where you said:

...The modules metadata folder is the only location checked - any version in `custom/<TheModule>/metadata/studio.php` is ignored.

#### Proposed fixes and/or additions

I think you must say:

...The modules metadata folder is the only location checked - any version in `custom/modules/<TheModule>/metadata/studio.php` is ignored.

**Comment by CBeechey** [comment]
@frnklnrd thanks for pointing this out, this has now been corrected.
