### ISSUE TITLE
Issue about Page developer/Vardefs.adoc

### ISSUE THREAD

**Issue by frnklnrd** [salesagility/SuiteDocs#93]
#### Page with Issue

https://docs.suitecrm.com/developer/vardefs/

#### What is wrong, less clear, or missing

In "Indices" area when you explain indices types, I think you must indicate if its possible include custom fields or not.

#### Proposed fixes and/or additions

And if it is possible you must indicate how to do that.

**Comment by pgorod** [comment]
I don't know enough to judge this or to write about this. I see some information here

http://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_8.0/Data_Framework/Vardefs/Working_With_Indexes/index.html

When you say "custom field", that would normally be created in a separate table (for example, `accounts_cstm` so I guess it won't be indexed in the `accounts` table. But I don't know if there's something in the code to handle that case...

Maybe @jimmackin can shed some light on this?

**Comment by JimMackin** [comment]
Unfortunately indexes on custom tables seem to be unsupported currently. :+1: on updating the docs to reflect this.

**Comment by pgorod** [comment]
Ok Jim I'll take care of updating the docs. Thanks for your help!

**Comment by frnklnrd** [comment]
Thanks, for help and dedication. ;)
