### ISSUE TITLE
Issue about Page developer/API/version-8/JSON-API.adoc

### ISSUE THREAD

**Issue by nikolastheo** [salesagility/SuiteDocs#96]
Thank you for this wonderful project, i found an issue with the JSON API.  Am using suitecrm Version 7.10.2 

#### Page with Issue
https://docs.suitecrm.com/developer/api/version-8/json-api/

#### What is wrong, less clear, or missing
/api/v8/modules/Accounts?filter[Accounts.contacts.date_modified]=[[gt]]2017-11-17T11:40:00+00:00
There is a typo in the documentation it should be contacts with lowercase that Contacts
Also, Relationship filtering does not work. i tried the example and got the following: 
```
{
    "errors": [
        {
            "code": 6000,
            "title": "[SuiteCRM] [InvalidArgumentException] [JsonApi][v1][Filters][Operators][Operator][hasOperator][expected type to be string] $operator",
            "status": 400
        }
    ],
    "meta": {
        "suiteapi": {
            "major": 8,
            "minor": 0,
            "patch": 0,
            "stability": "ALPHA"
        }
    },
    "jsonapi": {
        "version": "1.0"
    }
}
```
#### Proposed fixes and/or additions
Review the JSON API implementation

**Comment by CBeechey** [comment]
@nikolastheo thank you for raising this. The JSON API documentation is currently being updated. @zoltankocsardi can you confirm that these issues will be covered by the new documentation?

**Comment by pgorod** [comment]
Due to the many changes in the API code and the new documentation for it, I believe this is now out-dated.

If not, you can open a new issue, but please just make the suggested edits as a PR, it's easy:

https://docs.suitecrm.com/community/contributing-to-docs/

Thanks!
